### ISSUE TITLE
报错SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pluoluo** [cgy233/EthanHome-WOL#1]
您好，请教您一个问题。
我对代码不熟悉，使用了您这段代码，但是出现了一个问题，单独使用`wol.py`加`-p hostname `是可以唤醒主机的，但是通过`wol_mq.py`就会报错：
```
Received `on` from `ethanpc002` topic
  File "wol.py", line 41
    def __init__(self, *extra_search_paths, prefer_local_config=False, **config):
                                                              ^
SyntaxError: invalid syntax
256
```
这是怎么回事呢

**Comment by cgy233** [comment]
提示wol.py的参数错误，但是既然单独使用wol.py -p hostname命令行下可以唤醒，可以将wol_mq.py的17行的双引号内容更换为你在命令行下运行wol.py成功唤醒的命令，例如：print(os.system("python wol.py -p hostname"))

**Comment by pluoluo** [comment]
感谢！我已经发现问题在哪了，脚本是用python3写的，这里命令是python，所以会有语法错误

**Comment by cgy233** [comment]
好的，很高兴能帮到你。
