### ISSUE TITLE
ModuleNotFoundError: No module named 're'

### ISSUE THREAD

**Issue by Senboll-CD** [cgy233/EthanHome-WOL#2]
你好，在装MQTT依赖包的时候提示：
Traceback (most recent call last):
  File "/usr/bin/pip", line 3, in <module>
    import re
ModuleNotFoundError: No module named 're'

是python安装得有问题吗？

**Comment by cgy233** [comment]
注意Python2.7和python3.6的版本问题，你这个问题可能是使用了python2.7的pip，要使用pip3进行安装，如果提示没有安装pip3的话，如果是Ubuntu或debian可以使用命令apt install python3-pip进行安装

**Comment by Senboll-CD** [comment]
这个错误是在OpenWRT上出现的，安装的是Python3.10，我再研究一下。
目前是正常跑在CentOS上的。
谢谢你的回复。
