### ISSUE TITLE
心跳好像存在问题，过段时间会提示设备不在线，可openwrt进程中可以看到wol_mq.py是在后台运行

### ISSUE THREAD

**Issue by Morii-torri** [cgy233/EthanHome-WOL#3]
![image](https://user-images.githubusercontent.com/124775505/226162612-d4b9cbc8-9948-436f-a325-a6e7a5e5b927.png)

**Comment by cgy233** [comment]
程序正常运行的话，可能是MQTT连接的问题，我修改了连接的keepalive参数和订阅主题的qos，你更新再试试

**Comment by o9ltop** [comment]
巴法平台会挂掉，挂了后重连(on_connect)后没有subscribe,把subcribe写进on_connect可以解决

**Comment by onkncn** [comment]
> 程序正常运行的话，可能是MQTT连接的问题，我修改了连接的keepalive参数和订阅主题的qos，你更新再试试

巴法平台会挂掉，挂了后重连(on_connect)后没有subscribe,把subcribe写进on_connect可以解决

**Comment by cgy233** [comment]
> > 程序正常运行的话，可能是MQTT连接的问题，我修改了连接的keepalive参数和订阅主题的qos，你更新再试试
> 
> 巴法平台会挂掉，挂了后重连(on_connect)后没有subscribe,把subcribe写进on_connect可以解决

感谢提醒，前段时间太忙了，现在有空整理了一下，已将订阅放在连接服务器后执行，测试几天了暂无问题；
