### ISSUE TITLE
WIN10的SSH 可以选择加密吗，免密感觉太不安全了

### ISSUE THREAD

**Issue by kkelay** [cgy233/EthanHome-WOL#4]
免密感觉太不安全了，纯内网环境下还可以，

**Comment by cgy233** [comment]
从安全性上来讲，只要你不把家里面机器的端口开放，还是比较安全的，指令写死别给爆破问题都不大，现在的做法是将WIN10的SSH服务端的秘钥放在控制端做鉴权，从而实现的免密，不是什么设备都能免密登录WIN10。

**Comment by kkelay** [comment]
我想部署在公网上用，但是不太行，

**Comment by cgy233** [comment]
> 我想部署在公网上用，但是不太行，

不行，也不建议这么搞，非常不安全。

**Comment by kkelay** [comment]
已经搞完了，主要是本地没有合适的硬件来部署，用了几天 还可以，主要就是映射了 ssh端口和 网络唤醒的端口，
